# Schema for the configuration files of the Redirect after logout module.

redirect_after_logout.settings:
  type: config_object
  label: 'Redirect after logout settings'
  mapping:
    destination:
      type: path
      label: 'Redirect destination path.'
    message:
      type: text
      label: 'Redirect message.'
